FROM registry.access.redhat.com/ubi8:latest
RUN dnf install golang git -y
WORKDIR /go/src/github.com/mvazquezc/reverse-words/
COPY main.go .
COPY go.mod .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
EXPOSE 8080
USER 9999
CMD ["./main"]
