FROM registry.access.redhat.com/ubi8:latest
RUN dnf install golang git -y
WORKDIR /go/src/github.com/mvazquezc/reverse-words/
COPY main.go .
RUN go get github.com/gorilla/mux && go get github.com/prometheus/client_golang/prometheus/promhttp
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
EXPOSE 8080
CMD ["./main"]
